Update text for re-rebase

diff --git a/bin/git-rerebase b/bin/git-rerebase
--- a/bin/git-rerebase
+++ b/bin/git-rerebase
@@ -2,20 +2,19 @@
 
 # Check if params are sufficient enough to go ahead.
 targetBranch=$1
-test -z $targetBranch && echo "ERROR: Please provide the target branch with which you want to update your current branch." 1>&2 && exit 1
+test -z $targetBranch && echo "ERROR: Missing target branch!  Provide the target branch to re-rebase onto." 1>&2 && exit 1
 
 # Find which is your current branch
 if currentBranch=$(git symbolic-ref --short -q HEAD)
 then
   echo Pulling updates from the target branch $targetBranch ...
+  git remote update -p > /dev/null
+  git checkout $targetBranch > /dev/null
+  git pull > /dev/null
+  git checkout $currentBranch > /dev/null
 
-  git remote update -p
-  git checkout $targetBranch
-  git pull
-  git checkout $currentBranch
+  echo Re-rebasing $currentBranch onto $targetBranch...
   git rebase $targetBranch
-
-  echo Refreshed $currentBranch onto $targetBranch
 else
-  echo ERROR: Cannot find the current branch!
+  echo "ERROR: Cannot find the current branch!  Are you in a Git repository?" 1>&2 && exit 1
 fi
